# Generated by Django 4.1 on 2022-09-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task",
            field=models.CharField(max_length=400),
        ),
    ]
